---
kind: pipeline
type: docker
name: default

steps:
  - name: source
    image: debian:buster-slim
    commands:
      - apt-get update
      - apt-get install -y curl git jq
      - LATEST=$(curl -s https://api.github.com/repos/tidusjar/Ombi.Releases/releases | jq -r ".[0].tag_name")
      - if curl -sfL https://hub.docker.com/v2/repositories/ezkrg/ombi/tags/$LATEST > /dev/null; then echo "tag $LATEST already exist"; exit 78; fi
      - curl -sL --output ombi.tar.gz https://github.com/tidusjar/Ombi.Releases/releases/download/$LATEST/linux-x64.tar.gz
      - echo -n "$LATEST,latest" > .tags

  - name: release
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/ombi
    when:
      event:
      - cron
      cron:
      - nightly
---
kind: signature
hmac: 7a5166e4bc06b9dbfbb509b5b9189399014d292f413d12188d79f2a6294307b0

...
